### ISSUE TITLE
Support POST data persistence across pages for multi-step forms

### ISSUE THREAD

**Issue by theochr72** [sqlpage/SQLPage#661]
Hello,

I’m currently developing a website using SQLPage, but I’m facing an issue. I’m trying to implement a multi-step form where data needs to be passed from one page to the next. However, it seems impossible to retain or pass data across pages in POST without using a form, and storing data temporarily in the database isn’t a solution I’d like to use.

Is there an existing feature that could help with this, or perhaps an alternative solution to maintain POST data across pages in SQLPage?

Thank you very much for your assistance!

This structure should clearly present your issue and help the maintainers understand your request. Let me know if you’d like to add more details or context!

**Comment by lovasoa** [comment]
Hello, and welcome to SQLPage !
  Since this topic has come up before, I added [a new example for multi-step forms](https://github.com/sqlpage/SQLPage/tree/main/examples/forms-with-multiple-steps) to this repository.

It highlights the three main possibilities:
 - [Using a database table to store intermediate results](https://github.com/sqlpage/SQLPage/blob/main/examples/forms-with-multiple-steps/database)
 - [Using cookies](https://github.com/sqlpage/SQLPage/blob/main/examples/forms-with-multiple-steps/cookies)
 - [Using hidden form fields](https://github.com/sqlpage/SQLPage/blob/main/examples/forms-with-multiple-steps/hidden)

Since you mention you would like to avoid using a form element (because some of your form steps are simple links, I guess ?), the best solution for you is probably **cookies**.

**Comment by lovasoa** [comment]
Can you tell us more about your use case ? What are you building ? If your intermediate partially filled form state is very large, then the best solution is probably [database storage](https://github.com/sqlpage/SQLPage/blob/main/examples/forms-with-multiple-steps/database). All other solutions require repetitively sending the form state, which will be a bad user experience if it's very large and takes a long time to send.
